version: "{build}"
clone_folder: c:\projects\recode

environment:
  global:
    VERBOSE: 1 # Get test logs in output
  matrix:
    # - MSYSTEM: MSYS (no cython available)
    - MSYSTEM: MINGW64
    - MSYSTEM: MINGW32

init:
  - git config --global core.autocrlf input

install:
  - C:\msys64\usr\bin\bash.exe -l c:/projects/recode/build-aux/appveyor-install.sh

build_script:
  - C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/recode && ./bootstrap && ./configure --enable-silent-rules %CONFIGURE_FLAGS% && make && make DISTCHECK_CONFIGURE_FLAGS=\"%CONFIGURE_FLAGS%\" distcheck"
